/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uiautomation;

import com.codeborne.selenide.Configuration;
import org.hamcrest.MatcherAssert;
import org.junit.*;
import org.junit.Before;
//import org.junit.BeforeClass;
//import org.junit.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import static com.codeborne.selenide.CollectionCondition.size;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
import static org.junit.jupiter.api.Assertions.*;
import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.Condition.*;
//import static org.hamcrest.*;

class AppTest {
    //private static final String BASE_URL = "http://69.89.12.213:8080/reachuibgeTestAutomation/app/#app/";
    private static final String BASE_URL = "http://localhost:8080/reachuibgeTestAutomation/app/#app/";

    @BeforeClass
    public static void setup() {
        //Configuration.baseUrl = "http://69.89.12.213:8080/reachuibgeTestAutomation/app/#app/";
        Configuration.baseUrl = "http://localhost:8080/reachuibgeTestAutomation/app/#app/";
    }
    @BeforeEach
    public void setUp() {
        // Set authentication
        //System.setProperty("remote-debugging-port", "9515");
        //System.setProperty("webdriver.chrome.driver", "D:/cloud3tech/reachbuiAutomation/drivers/windows/chromedriver.exe");
        //System.setProperty("webdriver.chrome.driver", "/tmp/chromedriver_linux64/chromedriver");
        open("http://69.89.12.213:8080/reachuibgeTestAutomation/app/#app/login");
        //clearBrowserCookies();

        //WebDriverRunner.clearBrowserCache();
        $(By.name("username")).setValue("superuser_dev@bge.com");
        $(By.name("password")).setValue("tdev123");
        $(By.name("loginSubmit")).click();
        //screenshot("login.png");
    }
    @Test
    public void searchSubscriberEmptyValidation(){
        $(By.name("subscrSubmit")).click();
        MatcherAssert.assertThat($("#programAlert div").text(), is("Please enter at least one search criteria"));
    }
    /*@Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }*/
}
