/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uiautomation;

import com.codeborne.selenide.Configuration;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.hamcrest.MatcherAssert;
import org.junit.BeforeClass;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeOptions;
import org.springframework.boot.test.context.SpringBootTest;
import static org.hamcrest.MatcherAssert.assertThat;
import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selenide.*;

import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.open;
import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.*;

//@ExtendWith(SpringExtension.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class AppTest {
    WebDriverManager driver;
    private static final String BASE_URL = "http://69.89.12.213:8080/reachuibgeTestAutomation/app/#app/";
    //private static final String BASE_URL = "http://localhost:8080/reachuibgeTestAutomation/app/#app/";

    @BeforeAll
    static void setupAll() {
        WebDriverManager.chromedriver().setup();
        System.setProperty("--headless", "true");
        System.setProperty("--disable-dev-shm-usage", "true");
        System.setProperty("--no-sandbox", "true");
        System.setProperty("WebDriverManager.chrome.driver","/tmp/chromedriver_linux64/chromedriver");
    }
//    @AfterEach
//    void teardown() {
//        driver.quit();
//    }
    @BeforeClass
    public static void setup() {
        Configuration.baseUrl = "http://69.89.12.213:8080/reachuibgeTestAutomation/app/#app/";
        //Configuration.baseUrl = "http://localhost:8080/reachuibgeTestAutomation/app/#app/";
    }
    @BeforeEach
    public void setUp() {
        // Set authentication
        //open("http://69.89.12.213:8080/reachuibgeTestAutomation/app/#app/login");
        //System.setProperty("WebDriverManager.chrome.driver", "D:/cloud3tech/reachbuiAutomation/drivers/windows/chromedriver.exe");
        System.setProperty("WebDriverManager.chrome.driver","/tmp/chromedriver_linux64/chromedriver");
        System.setProperty("--headless", "true");
        System.setProperty("--disable-dev-shm-usage", "true");
        System.setProperty("--no-sandbox", "true");
        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("useAutomationExtension", false);
        //WebDriver driver = new ChromeDriver(options);
        //driver.get(BASE_URL);
        open(BASE_URL+"login");
        //clearBrowserCookies();
        //WebDriverRunner.clearBrowserCache();
        $(By.name("username")).setValue("superuser_dev@bge.com");
        $(By.name("password")).setValue("tdev123");
        $(By.name("loginSubmit")).click();
        //screenshot("login.png");
    }
    @Test
    public void SubscriberSearchEmptyValidation(){
        $(By.name("subscrSubmit")).click();
        MatcherAssert.assertThat($("#programAlert div").text(), is("Please enter at least one search criteria"));
    }
    @Test
    public void searchSubscriberPositiveResult() {
        //open("subscribers");
        $(By.className("ra-well-title")).shouldHave(text("Search Criteria"));
        //getWebDriver().findElement(By.id("customerNumber"));
        $(By.name("customerNumber")).setValue("xxx0000001");
        $(By.name("subscrSubmit")).click();
        $(By.className("k-loading-image")).shouldBe(visible);
        assertThat($(".k-pager-info").text(), is("No items to display"));
        $(By.name("customerNumber")).setValue("0000000102");
        $(By.name("subscrSubmit")).click();
        $(By.className("k-loading-image")).shouldBe(visible);
        //screenshot("SubSrchLoadding.png");
        //sleep(6000);
        //assertThat($(".k-pager-info").text(), is("1 - 1 of 1 items"));
        $(By.className("k-pager-info")).shouldHave(text("items"));
        //screenshot("SubSrchWithResult.png");
    }
    @Test
    public void searchSubscriberFirstnameNegative() {
        //open("subscribers");
        $(By.className("ra-well-title")).shouldHave(text("Search Criteria"));
        $(By.id("firstName")).setValue("a");
        $(By.name("subscrSubmit")).click();
        //screenshot("FirstnameErrorMessage.png");
        //assertThat($(".k-pager-info").text(), is("1 - 1 of 1 items"));
        $("#programAlert div").shouldHave(text("Please enter minimum 3 characters."));
        $(By.id("firstName")).setValue("aa");
        $(By.name("subscrSubmit")).click();
        $("#programAlert div").shouldHave(text("Please enter minimum 3 characters."));
    }
    @Test
    public void searchSubscriberLastnameNegative() {
        //open("subscribers");
        $(By.className("ra-well-title")).shouldHave(text("Search Criteria"));
        $(By.id("lastName")).setValue("a");
        $(By.name("subscrSubmit")).click();
        $("#programAlert div").shouldHave(text("Please enter minimum 3 characters."));
        $(By.id("lastName")).setValue("aa");
        $(By.name("subscrSubmit")).click();
        $("#programAlert div").shouldHave(text("Please enter minimum 3 characters."));
    }
    @Test
    public void searchSubscriberCustNoNegative() {
        //open("subscribers");
        $(By.className("ra-well-title")).shouldHave(text("Search Criteria"));
        $(By.id("customerNumber")).setValue("a");
        $(By.name("subscrSubmit")).click();
        $("#programAlert div").shouldHave(text("Please enter minimum 3 characters."));
        $(By.id("customerNumber")).setValue("aa");
        $(By.name("subscrSubmit")).click();
        $("#programAlert div").shouldHave(text("Please enter minimum 3 characters."));
        assertThat($(By.id("customerNumber")).getAttribute("maxlength"), is("10"));
    }
    @Test
    public void searchSubscriberAccNoNegative() {
        //open("subscribers");
        $(By.className("ra-well-title")).shouldHave(text("Search Criteria"));
        $(By.id("accountID")).setValue("a");
        $(By.name("subscrSubmit")).click();
        $("#programAlert div").shouldHave(text("Please enter minimum 3 characters."));
        $(By.id("accountID")).setValue("aa");
        $(By.name("subscrSubmit")).click();
        $("#programAlert div").shouldHave(text("Please enter minimum 3 characters."));
        assertThat($(By.id("accountID")).getAttribute("maxlength"), is("11"));
    }
    /*@Test
    public void addContactAtrrMaxlengthExist() {
        open("subscribers");
        $(By.className("ra-well-title")).shouldHave(text("Search Criteria"));
        $(By.name("customerNumber")).setValue("0000000102");
        $(By.name("subscrSubmit")).click();
        $(By.className("k-loading-image")).shouldBe(visible);
        $(By.className("k-loading-image")).shouldBe(disappear);
        $(By.className("k-pager-info")).shouldHave(text("items"));
        //sleep(36000);
        $(By.className("view-det-btn")).shouldBe(visible);
        $(By.className("view-det-btn"),0).click();
        $(By.id("subDetDiv")).shouldNotHave(attribute("class", "ng-hide"));
        $(By.className("k-loading-image")).shouldBe(visible);
        $(By.className("k-loading-image")).shouldBe(disappear);
        sleep(4000);
        $(".pref-refresh span").shouldHave(text("Refresh"));
        $(By.id("subDetContViewTab")).click();
        $(By.id("addNewContSms")).shouldBe(visible);
        $(By.id("addNewContSms")).click();
        $(".modelButtonFloatRight button").shouldBe(visible);
        // sleep(1000);
        $(By.id("contactLabel")).shouldHave(attribute("maxlength"));
    }

   @Test //kendo drop down selection issue still pending
    public void contactSearchPush() {
        open("subscribers");
        $(By.className("cont-srch")).click();
        $(By.id("cnt-title")).shouldHave(text("Search Criteria"));
        //$(By.id("notificationContactTypeChannel")).shouldBe(visible);
        $(By.id("notificationContactTypeChannel")).selectOptionByValue("Push");
       // $(By.id("contactSearch")).setValue("BGE_1233456");
        //$(By.id("subscriberContactFromDate")).setValue("2020-04-01");
       // screenshot("con-srch-push-negative.png");
        $(By.id("contactSubBtn")).click();
    }*/
}
